name: Build
on: [push]

jobs:
  lib:
    name: Build lib
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - run: cd packages/react-ui
      - name: Test
        run: yarn test
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - run: cd packages/docs
      - name: Test
        run: yarn test
